print("hola esto es python") #AQUI LE INDICAMOS QUE QUEREMOS QUE NOS PROYECTE EN PANTALLA LO QUE ESTE ESCRITO DONTRO DE LOS PARENTESIS .

print("hOLA SOY ALEJANDRO Y TENGO 21 AÑOS")


#OPERACIONES MATEMATICAS.

print( 12 + 5) #INDICAMOS QUE NOS MUESTRE UNA SUMA.

print(10 - 7) #INDICAMOS  QUE NOS MUESTRE UNA RESTA. 

print(5 * 8) #INDICAMOS QUE NOS MUESTRE UNA MULTIPLICACION.

print(25 / 5) #INDICAMOS QUE NOS MUESTRE UNA DIVICION.



"""
USAMOS ESTO PARA PONER UN COMENTARIO DE VARIAS 
LIENAS SIN USAR EL #

"""