print("HOLA, BIENBENIDO")

#COLOCAMOS UNA VARIABLE

name = "Alejandro"
print(name)


#VARIABLE PARA NUMEROS

age = 21
print(age)

#COLOCAMOS OTRA VARIABLE DE TEXTO O NOMBRE

name = "Moreno"
print("AQUI CAMBIAMOS LA VARIABLE", name)

#input

"""EL INPUT NOS SIRVE PARA PODER PEDIR QUE EL USUARIO COLOQUE EL VALOR A DECLARAR DENTRO DE LA VARIABLE."""
#EL INPUT NOS SIRVE PARA PODER PEDIR QUE EL USUARIO COLOQUE EL VALOR A DECLARAR DENTRO DE LA VARIABLE.


name = input("what's your name?")
print("usando el input", name)